name: Build
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        include:
          # - os: ubuntu-latest
          #   file: pocket-relay-plugin-installer
          #   file_name: Ubuntu Build
          - os: windows-latest
            file: pocket-relay-plugin-installer.exe
            file_name: Windows Build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Build Client
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file_name }}
          path: "./target/debug/${{ matrix.file }}"
